modLoader="javafml"
loaderVersion="[47,)"
license="MIT LICENSE"
issueTrackerURL="https://github.com/RavenholmZombie/RZCraft-Additions/issues"

[[mods]]
modId="rzadditions"
version="1.0.2"
displayName="RZ's Additions"
authors="RavenholmZombie"
description='''
A simple mod that adds simple stuff.
'''
logoFile="rza.png"

[[dependencies.rzadditions]]
modId="forge"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.rzadditions]]
modId="flywheel"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.rzadditions]]
modId="create"
mandatory=true
versionRange="[0.5.1.e,)"
ordering="NONE"
side="BOTH"

[[dependencies.rzadditions]]
modId="resourcefullib"
mandatory=true
versionRange="[2.1.29,)"
ordering="NONE"
side="BOTH"

[[dependencies.rzadditions]]
modId="botarium"
mandatory=true
versionRange="[2.3.4,)"
ordering="NONE"
side="BOTH"